// src/constants/routes.ts
export const ROUTES = {
    HOME: '/',
    PERSONAL_LOAN: '/personal-loan',
    BUSINESS_LOAN: '/business-loan',
    HOME_LOAN: '/home-loan',
    CAR_LOAN: '/car-loan',
    EDUCATION_LOAN: '/education-loan',
    MACHINERY_LOAN: '/machinery-loan',
    HEALTH_INSURANCE: '/health-insurance',
    VEHICLE_INSURANCE: '/vehicle-insurance',
    LIFE_INSURANCE: '/life-insurance',
    APPLICATION: '/application',
    CONTACT: '/contact',
    PARTNER: '/partner',
    CAREERS: '/careers',
    TESTIMONIAL: '/reviews',
    CURRENCY_CONVERTER: '/currency-converter',
    IFSC_CODE_FINDER: '/ifsc-code',
    CALCULATORS: {
        HOME_LOAN: '/calculators/home-loan',
        PERSONAL_LOAN: '/calculators/personal-loan',
        BUSINESS_LOAN: '/calculators/business-loan',
        AUTOMOBILE_LOAN: '/calculators/automobile-loan',
        FD: '/calculators/fd',
        INSURANCE: '/calculators/insurance',
        MUTUAL_FUND: '/calculators/mutual-fund',
        CREDIT_CARD: '/calculators/credit-card',
    },
    BLOGS: '/blogs',
    BLOG_POST: (slug: string) => `/blogs/${slug}`,
} as const;