/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsletterIndexRouteImport } from './routes/newsletter.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TagSlugRouteImport } from './routes/tag/$slug'
import { Route as NewsletterPersonalizeRouteImport } from './routes/newsletter.personalize'
import { Route as NewsletterConfirmRouteImport } from './routes/newsletter.confirm'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as ArticleSlugRouteImport } from './routes/article/$slug'
import { Route as AdminNewslettersRouteImport } from './routes/admin/newsletters'
import { Route as AdminAccessRouteImport } from './routes/admin/access'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterIndexRoute = NewsletterIndexRouteImport.update({
  id: '/newsletter/',
  path: '/newsletter/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterPersonalizeRoute = NewsletterPersonalizeRouteImport.update({
  id: '/newsletter/personalize',
  path: '/newsletter/personalize',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmRoute = NewsletterConfirmRouteImport.update({
  id: '/newsletter/confirm',
  path: '/newsletter/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewslettersRoute = AdminNewslettersRouteImport.update({
  id: '/admin/newsletters',
  path: '/admin/newsletters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/admin/access',
  path: '/admin/access',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/search': typeof SearchRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/newsletters': typeof AdminNewslettersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/newsletter/personalize': typeof NewsletterPersonalizeRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/newsletter/': typeof NewsletterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/search': typeof SearchRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/newsletters': typeof AdminNewslettersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/newsletter/personalize': typeof NewsletterPersonalizeRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin': typeof AdminIndexRoute
  '/newsletter': typeof NewsletterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/search': typeof SearchRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/newsletters': typeof AdminNewslettersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/newsletter/personalize': typeof NewsletterPersonalizeRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/newsletter/': typeof NewsletterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blogs'
    | '/search'
    | '/admin/access'
    | '/admin/newsletters'
    | '/article/$slug'
    | '/category/$slug'
    | '/newsletter/confirm'
    | '/newsletter/personalize'
    | '/tag/$slug'
    | '/admin/'
    | '/newsletter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blogs'
    | '/search'
    | '/admin/access'
    | '/admin/newsletters'
    | '/article/$slug'
    | '/category/$slug'
    | '/newsletter/confirm'
    | '/newsletter/personalize'
    | '/tag/$slug'
    | '/admin'
    | '/newsletter'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/blogs'
    | '/search'
    | '/admin/access'
    | '/admin/newsletters'
    | '/article/$slug'
    | '/category/$slug'
    | '/newsletter/confirm'
    | '/newsletter/personalize'
    | '/tag/$slug'
    | '/admin/'
    | '/newsletter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BlogsRoute: typeof BlogsRoute
  SearchRoute: typeof SearchRoute
  AdminAccessRoute: typeof AdminAccessRoute
  AdminNewslettersRoute: typeof AdminNewslettersRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  NewsletterConfirmRoute: typeof NewsletterConfirmRoute
  NewsletterPersonalizeRoute: typeof NewsletterPersonalizeRoute
  TagSlugRoute: typeof TagSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  NewsletterIndexRoute: typeof NewsletterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/': {
      id: '/newsletter/'
      path: '/newsletter'
      fullPath: '/newsletter/'
      preLoaderRoute: typeof NewsletterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/personalize': {
      id: '/newsletter/personalize'
      path: '/newsletter/personalize'
      fullPath: '/newsletter/personalize'
      preLoaderRoute: typeof NewsletterPersonalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirm': {
      id: '/newsletter/confirm'
      path: '/newsletter/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof NewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletters': {
      id: '/admin/newsletters'
      path: '/admin/newsletters'
      fullPath: '/admin/newsletters'
      preLoaderRoute: typeof AdminNewslettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BlogsRoute: BlogsRoute,
  SearchRoute: SearchRoute,
  AdminAccessRoute: AdminAccessRoute,
  AdminNewslettersRoute: AdminNewslettersRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  NewsletterConfirmRoute: NewsletterConfirmRoute,
  NewsletterPersonalizeRoute: NewsletterPersonalizeRoute,
  TagSlugRoute: TagSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  NewsletterIndexRoute: NewsletterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
